name: Benchmark

on:
  workflow_dispatch:

jobs:
  Benchmark:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install latest finufft
      run: pip install --upgrade finufft
    - name: Install latest finufft-benchmark
      run: pip install --upgrade finufft-benchmark
    - name: run benchmark
      run: finufft-benchmark run --config config.yml
