name: Benchmark

on:
  workflow_dispatch:

jobs:
  Benchmark:
    runs-on: trop

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'scratchrealm/finufft-benchmark'
    - name: Install finufft
      run: pip install finufft
    - name: Install finufft-benchmark
      run: pip install .
    - name: run benchmark
      run: finufft-benchmark run
